#!/bin/sh
# build_session_context.sh — synthesize the workspace's startup context into one file
#
# What this does:
#   Codex does not have @-imports like Claude Code. The closest equivalent is
#   config.toml's developer_instructions block, which is static. This script
#   builds a deterministic session-context.md that Codex reads at session start
#   (referenced from developer_instructions). Run this script whenever the
#   underlying files change — or wire it into a git pre-commit hook.
#
# Output:
#   memory/session-context.md
#
# Usage:
#   tools/scripts/build_session_context.sh
#   (run from the workspace root, OR from anywhere — the script cd's to the
#    workspace root automatically)
#
# Exit codes:
#   0  success
#   1  workspace structure not detected
#   2  required input file missing
#
# Idempotent: safe to run repeatedly.

set -eu

# Locate workspace root: the directory containing core/, memory/, and LAUNCHER.md
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ ! -d "$ROOT/core" ] || [ ! -d "$ROOT/memory" ] || [ ! -f "$ROOT/LAUNCHER.md" ]; then
    echo "ERROR: workspace structure not detected at $ROOT" >&2
    echo "Expected core/, memory/, and LAUNCHER.md" >&2
    exit 1
fi

OUT="$ROOT/memory/session-context.md"
TMP="$OUT.tmp.$$"

# Required inputs — failure if any is missing
required_files() {
    cat <<EOF
core/constitution.md
core/ALGORITHM.md
core/ISC.md
core/effort-tiering.md
core/verification-doctrine.md
core/decision-rules.md
memory/identity.md
memory/current-focus.md
LAUNCHER.md
EOF
}

# Verify every required file exists before writing anything
for f in $(required_files); do
    if [ ! -f "$ROOT/$f" ]; then
        echo "ERROR: required file missing: $f" >&2
        exit 2
    fi
done

# Build the synthesized context — header, then concatenated content with section dividers
{
    cat <<HEADER
---
title: Session Context (synthesized)
type: synthesized
domain: dai
product: DAI
audience: codex
owner: team
status: active
updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
tags:
  - session-context
  - synthesized
  - codex-startup
artifact_type: synthesized-context
generated_by: tools/scripts/build_session_context.sh
generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
warning: do-not-edit-by-hand
---

# Session Context — Synthesized

This file is regenerated by \`tools/scripts/build_session_context.sh\`.
**Do not edit by hand.** Edit the source files in \`core/\` and \`memory/\` instead.

This is the single file Codex should read at session start. It catenates the
workspace's startup-essential context into one deterministic block. Editing
sources and re-running the script is how the team updates Codex's behavior
across sessions.

---

HEADER

    # Concatenate each required file, each preceded by a divider naming its source
    for f in $(required_files); do
        printf '\n\n========================================\n'
        printf '## Source: %s\n' "$f"
        printf '========================================\n\n'
        cat "$ROOT/$f"
    done

    # Skills catalog — prefer the auto-generated catalog if present, else fall back to skills-map.md
    if [ -f "$ROOT/memory/skills-catalog.md" ]; then
        printf '\n\n========================================\n'
        printf '## Source: memory/skills-catalog.md (auto-generated)\n'
        printf '========================================\n\n'
        cat "$ROOT/memory/skills-catalog.md"
    elif [ -f "$ROOT/skills/skills-map.md" ]; then
        printf '\n\n========================================\n'
        printf '## Source: skills/skills-map.md (catalog)\n'
        printf '========================================\n\n'
        cat "$ROOT/skills/skills-map.md"
    fi

    # EFFECTUS pointer — list the seven seed files but do not catenate them; they're read on-demand
    if [ -f "$ROOT/memory/effectus/effectus-map.md" ]; then
        printf '\n\n========================================\n'
        printf '## Pointer: memory/effectus/ (read on-demand)\n'
        printf '========================================\n\n'
        printf 'EFFECTUS is the deeper substrate of team intent. Read on-demand when leverage matters.\n\n'
        for f in "$ROOT/memory/effectus"/*.md; do
            [ -f "$f" ] || continue
            rel="${f#$ROOT/}"
            printf '%s\n' "- \`$rel\`"
        done
    fi

    # Active-work-map for current direction
    if [ -f "$ROOT/active-work-map.md" ]; then
        printf '\n\n========================================\n'
        printf '## Source: active-work-map.md\n'
        printf '========================================\n\n'
        cat "$ROOT/active-work-map.md"
    fi

    printf '\n\n---\n_end of synthesized context_\n'
} > "$TMP"

mv "$TMP" "$OUT"

LINES=$(wc -l < "$OUT")
BYTES=$(wc -c < "$OUT")
echo "Wrote $OUT — $LINES lines, $BYTES bytes"
echo "Wire into Codex via config.toml developer_instructions. See core/CODEX_INTEGRATION.md."
