#!/bin/sh
# skills_index.sh — emit a one-line-per-skill catalog from skills/*/SKILL.md
#
# What this does:
#   Walks skills/*/SKILL.md, extracts the YAML frontmatter `name` and
#   `description` fields, and emits a single-line summary per skill. The output
#   is meant to be embedded in memory/session-context.md so Codex has a
#   one-shot view of what's available without reading every SKILL.md.
#
# Output mode:
#   default        — write to memory/skills-catalog.md (idempotent)
#   --stdout       — print to stdout only
#   --check        — exit 1 if any SKILL.md is missing name or description
#
# Usage:
#   tools/scripts/skills_index.sh
#   tools/scripts/skills_index.sh --stdout
#   tools/scripts/skills_index.sh --check
#
# Exit codes:
#   0  success
#   1  workspace structure not detected, or --check found a missing field
#
# Idempotent: safe to run repeatedly.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ ! -d "$ROOT/skills" ] || [ ! -f "$ROOT/LAUNCHER.md" ]; then
    echo "ERROR: workspace structure not detected at $ROOT" >&2
    exit 1
fi

MODE="file"
case "${1:-}" in
    --stdout) MODE="stdout" ;;
    --check)  MODE="check"  ;;
    "") ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
esac

# Extract a single frontmatter field value from a SKILL.md.
# Reads only lines between the opening '---' and the closing '---'.
extract_field() {
    file="$1"
    field="$2"
    awk -v f="$field" '
        BEGIN { in_fm = 0; depth = 0 }
        /^---[[:space:]]*$/ {
            depth++
            if (depth == 1) { in_fm = 1; next }
            if (depth == 2) { in_fm = 0; exit }
        }
        in_fm && $0 ~ "^" f ":" {
            sub("^" f ":[[:space:]]*", "")
            sub(/^["'\'']/, "")
            sub(/["'\'']$/, "")
            print
            exit
        }
    ' "$file"
}

generate() {
    NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    cat <<FRONTMATTER
---
title: Skills Catalog
type: synthesized
domain: dai
product: DAI
audience: team
owner: team
status: active
updated: $NOW
tags:
  - skills
  - catalog
  - auto-generated
artifact_type: skills-catalog
generated_by: tools/scripts/skills_index.sh
warning: do-not-edit-by-hand
---

FRONTMATTER
    printf '# Skills Catalog (auto-generated)\n\n'
    printf '_Generated by `tools/scripts/skills_index.sh` — do not edit by hand._\n\n'
    printf 'One line per skill. Read `skills/{name}/SKILL.md` for full workflow.\n\n'

    found_any=0
    for skill_dir in "$ROOT/skills"/*/; do
        [ -d "$skill_dir" ] || continue
        skill_md="${skill_dir}SKILL.md"
        if [ ! -f "$skill_md" ]; then
            continue
        fi
        name="$(extract_field "$skill_md" "name")"
        desc="$(extract_field "$skill_md" "description")"
        rel_path="${skill_md#$ROOT/}"
        if [ -z "$name" ]; then
            name="$(basename "$skill_dir")"
        fi
        if [ -z "$desc" ]; then
            desc="(no description in frontmatter)"
        fi
        printf -- '- **%s** — %s _(see `%s`)_\n' "$name" "$desc" "$rel_path"
        found_any=1
    done

    if [ "$found_any" -eq 0 ]; then
        printf '_No skills with SKILL.md found._\n'
    fi
}

check_completeness() {
    failures=0
    for skill_dir in "$ROOT/skills"/*/; do
        [ -d "$skill_dir" ] || continue
        skill_md="${skill_dir}SKILL.md"
        skill_name="$(basename "$skill_dir")"
        if [ ! -f "$skill_md" ]; then
            echo "MISSING SKILL.md: $skill_name" >&2
            failures=$((failures + 1))
            continue
        fi
        name="$(extract_field "$skill_md" "name")"
        desc="$(extract_field "$skill_md" "description")"
        if [ -z "$name" ];  then echo "MISSING name:        $skill_name"        >&2; failures=$((failures + 1)); fi
        if [ -z "$desc" ];  then echo "MISSING description: $skill_name"        >&2; failures=$((failures + 1)); fi
    done
    if [ "$failures" -gt 0 ]; then
        echo "$failures problem(s) found." >&2
        exit 1
    fi
    echo "All skills have name + description in frontmatter."
}

case "$MODE" in
    stdout)
        generate
        ;;
    check)
        check_completeness
        ;;
    file)
        OUT="$ROOT/memory/skills-catalog.md"
        TMP="$OUT.tmp.$$"
        generate > "$TMP"
        mv "$TMP" "$OUT"
        LINES=$(wc -l < "$OUT")
        echo "Wrote $OUT — $LINES lines"
        ;;
esac
